services:
  db:
    image: postgres:17.1
    volumes:
      - postgres-main:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - '5433:5432'


  app:
    build: .
    command: >
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done;
      python3 manage.py migrate;
      python3 manage.py runserver 0.0.0.0:8000;
      '
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - db
    restart: always
    ports:
      - '8000:8000'


  nginx:
    command: nginx -g "daemon off;"
    depends_on:
      - app
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - media:/var/www/app/media
      - static:/var/www/app/static
    ports:
      - "127.0.0.1:8500:80"


volumes:
  postgres-main:
  static:
  media: